<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<br>
<!--<button><a href="--><?php //echo base_path; ?><!--/?ct=log-in&act=log-out">Đăng xuât</a></button>-->
<h1>Đây là trang chủ Login của nick GIÁO VIÊN !!!</h1>

<button><a href="<?php echo base_path; ?>/?ct=home-log-gv&act=show-info-gv">Thông tin cá nhân</a></button>
<button><a href="<?php echo base_path; ?>/?ct=home-log-gv&act=add-sv">Thêm sinh viên</a></button>
<button><a href="<?php echo base_path; ?>/?ct=home-log-gv&act=show-ds-sv">Danh sách sinh viên</a></button>
<button><a href="<?php echo base_path; ?>/?ct=home-log-gv&act=diem-danh">Điểm danh</a></button>
<button><a href="<?php echo base_path; ?>/?ct=home-log-gv&act=giao-bai&stt=1">Giao bài</a></button>
<button><a href="<?php echo base_path; ?>/?ct=home-log-gv&act=bai-tap">Bài tập</a></button>

</body>
</html>





