<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

<br>

<button><a href="<?php echo base_path; ?>/?ct=log-in&act=log-out">Đăng xuât</a></button>
<h1>Đây là trang chu Login của nick SINH VIÊN !!!</h1>

<button><a href="<?php echo base_path; ?>/?ct=home-log-sv&act=show-info-sv">Thông tin cá nhân</a></button>
<button><a href="<?php echo base_path; ?>/?ct=home-log-sv&act=bai-tap">Bài tập</a></button>


</body>
</html>






